{
 "title": "JVM Thread States",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "measurement", "query": "show measurements" },
   {
    "name": "TaskID_Connection_preferences",
    "query": "select DISTINCT(\"task\") from (select \"task\", \"state\",\"blockedCount\" from $measurement WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  { "title": "Thread States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thread States | TASK ID $TaskID_Connection_preferences",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "task",
       "operator": "=~",
       "value": "/^$TaskID_Connection_preferences$/"
      }
     ]
    }
   ]
  },
  { "title": "Contention Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Blocked count | TASK ID $TaskID_Connection_preferences",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread_states",
     "select": [
      [
       { "params": [ "blockedCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "task",
       "operator": "=~",
       "value": "/^$TaskID_Connection_preferences$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocked count All | TASK ID $TaskID_Connection_preferences",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread_states",
     "select": [
      [
       { "params": [ "blockedCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "task",
       "operator": "=~",
       "value": "/^$TaskID_Connection_preferences$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocked time | TASK ID $TaskID_Connection_preferences",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread_states",
     "select": [
      [
       { "params": [ "blockedTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "task",
       "operator": "=~",
       "value": "/^$TaskID_Connection_preferences$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocked time All | TASK ID $TaskID_Connection_preferences",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread_states",
     "select": [
      [
       { "params": [ "blockedTime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "task",
       "operator": "=~",
       "value": "/^$TaskID_Connection_preferences$/"
      }
     ]
    }
   ]
  },
  {
   "title": "JVMThreadStateRecorder Internal Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Time to Get Thread States by Task",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Task ID $tag_task",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_to_get_thread_states",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}