version: '3.3'
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=JVMThreadStatesRecorder
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  jvmthreadstatesrecorder:
    build: .
    depends_on:
      - influxdb
    network_mode: host

volumes:
  influxdb-storage:
  grafana-storage: